"use client";

import localFont from "next/font/local";
import "./globals.css";
import { useEffect, useState } from "react";
import LoadingOverlay from "./components/LoadingOverlay"; // Đảm bảo file tồn tại
import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({ children }) {
  const [loading, setLoading] = useState(false);
  const [hasPlayedFirstVideo, setHasPlayedFirstVideo] = useState(false); // Trạng thái video đầu tiên
  const pathname = usePathname();

  useEffect(() => {
    if (!hasPlayedFirstVideo) {
      // Nếu video chưa chạy, không bật loading
      return;
    }

    setLoading(true);

    const timer = setTimeout(() => {
      setLoading(false);
    }, 1000); // Ẩn loading sau 1 giây

    return () => clearTimeout(timer);
  }, [pathname, hasPlayedFirstVideo]);

  const handleVideoPlay = () => {
    setHasPlayedFirstVideo(true); // Video đầu tiên đã chạy xong
  };

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Hiển thị overlay chỉ nếu video chưa chạy */}
        {loading && !hasPlayedFirstVideo && <LoadingOverlay />}

        {/* Video đầu tiên */}
        {!hasPlayedFirstVideo && (
          <video
            autoPlay
            muted
            preload="auto"
            playsInline
            onCanPlay={() => handleVideoPlay()} // Đánh dấu video đã chạy
            className="hidden"
          >
            <source src="/Logo-3-[remix].mp4" type="video/mp4" />
          </video>
        )}

        {/* Nội dung trang */}
        {children}
      </body>
    </html>
  );
}
